=== schneemax/pubDoc/Assessment_1/Kapitel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Kapitel">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="kapitel" type="kapiteltyp" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="kapiteltyp">
    <xs:sequence>
      <xs:element name="absatz" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="kapitel" type="kapiteltyp" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== schneemax/pubDoc/Assessment_1/Kapitel.xml
<?xml version="1.0" encoding="UTF-8"?>
<Kapitel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Kapitel.xsd">
	<kapitel>
		<absatz>Dies ist ein kurzer Text, der in XML strukturiert ist. Dieser Text soll Ihnen als Uebungsmaterial dienen, um einige grundlegende Regeln beim Gebrauch von XML anzuwenden.</absatz>
		<absatz>In diesem Abschnitt lernen Sie, was alles zu beachten ist, um ein fehlerfreies XML-Dokument zu erzeugen.</absatz>
		<absatz>Zu beachten sind die Eigenschaften der Wohlgeformtheit und der Gueltigkeit.</absatz>
	</kapitel>
<kapitel>
	<absatz>Die Wohlgeformtheit richtet sich auf die Einhaltung gewisser Grundregeln, die jedes XML-Dokument einhalten muss. Sie ist unabhaengig von einer bestimmten Dokumenttypdefinition (DTD) oder einem bestimmten XML-Schema.</absatz>
	<absatz>Die Gueltigkeit richtet sich auf die Uebereinstimmung mit einer bestimmten DTD bzw. einem bestimmten XML-Schema. Damit die Gueltigkeit ueberprueft werden kann, muss das XML-Dokument mit einer DTD bzw. einem XML-Schema verbunden werden. Dies kann etwa dadurch geschehen, dass aus dem Dokument heraus auf ein Definitionsdokument verwiesen wird.</absatz>
</kapitel>
</Kapitel>
